import "./globals.css";
import type { Metadata } from "next";
import Provider from "./components/Provider";

export const metadata: Metadata = {
  title: "Lumina-Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-screen h-screen flex">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
